return {
    ["Poop"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/refs/heads/main/poop.lua",
    ["Sharp 6"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/refs/heads/main/SHARP%206.lua",
    ["Sharp 11"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/refs/heads/main/SHARP%2011.lua",
    ["Split jump"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/refs/heads/main/split%20jump.lua",
    ["Anim2"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/refs/heads/main/anim2.lua",
    ["Flip"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/refs/heads/main/flip.lua",
    ["9mm Go Bang!"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/9mm%20Go%20Bang%21%2Elua",
    ["A Bar Song"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/A%20Bar%20Song%2Elua",
    ["A Loving Present"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/A%20Loving%20Present%2Elua",
    ["A Tear In Space"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/A%20Tear%20In%20Space%2Elua",
    ["A Tear In Space (Airlock)"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/A%20Tear%20In%20Space%20%28Airlock%29%2Elua",
    ["A Vlog"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/A%20Vlog%2Elua",
    ["A Warrior Prepares"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/A%20Warrior%20Prepares%2Elua",
    ["A dice"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/A%20dice%2Elua",
    ["AFK"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/AFK%2Elua",
    ["APT"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/APT%2Elua",
    ["APT Dance"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/APT%20Dance%2Elua",
    ["APT V2"] = "https://raw.githubusercontent.com/0riginalWarrior/Animations/main/APT%20V2%2Elua",
}
